// 1601N/Vue/TodoList/src/components/Input.vue
<template>
    <div>
        <input type="text" placeholder="todo..." v-model="text">
        <button @click="saveData">保存</button>
    </div>
</template>
<script>
    import {mapState} from 'vuex';
    export default {
        data(){
            return {
                text: ''
            }
        },
        // computed: mapState({
        //     todoText: state=>state.input.text
        // }),
        watch: {
            text(){
                console.log('text changeed');
                this.$store.commit('changeText', this.text);
            }
        },
        methods: {
            saveData(){
                // console.log('text...', this.text);
                // 用commit命令触发mutation
                this.$store.commit('saveData', this.text);
            }
        },
        mounted(){
            console.log(this.$store);
        }
    }
</script>

// 1602B/React/todo_redux/src/components/Input.jsx
import React from 'react';
import {connect} from 'react-redux';


class Input extends React.Component{
    constructor(){
        super();
    }

    changeText(e){
        // console.log(e.target.value);
        this.props.changeText(e.target.value);
    }

   
    render(){
        // console.log('this.props...', this.props);
        return <div>
            <input type="text" placeholder="todo..." value={this.props.text} onChange={(e)=>{this.changeText(e)}}/>
            <button onClick={this.props.save}>保存</button>
        </div>
    }
}
const mapStateToProps = (state, ownProps)=>{
    console.log('state...', state, ownProps);
    return {
        text: state.text
    }
}

const mapDispatchToProps = (dispatch)=>{
    return {
        changeText: (text)=>dispatch({
            type: 'CHANGE_TEXT',
            payload: {
                text
            }
        }),
        save: ()=>dispatch({
            type: 'ADD_LIST'
        })
    }
}


export default connect(mapStateToProps, mapDispatchToProps)(Input)
