// 1601N/Vue/TodoList/src/components/List.vue
<template>
    <div>
        <ul>
            <li v-for="(item, index) in list" :key="index">{{item}}</li>
        </ul>
    </div>
</template>
<script>
    import {mapState} from 'vuex';
    export default {
        // 用mapState方法获取state
        computed: mapState({
            list: state=>state.list.list
        })
    }
</script>

// 1602B/React/todo_redux/src/components/List.jsx
import React from 'react';
import {connect} from 'react-redux';


class List extends React.Component{
    constructor(){
        super();
    }
   
    render(){
       return <div>{
           this.props.list.map((item, index)=>{
               return <li key={index}>{item}</li>
           })
       }</div>
    }
}
const mapStateToProps = (state, ownProps)=>{
    return {
        list: state.list
    }
}

const mapDispatchToProps = (dispatch)=>{
    return {
      
    }
}


export default connect(mapStateToProps, mapDispatchToProps)(List)
