// 1601N/Vue/TodoList/src/App.vue
<template>
  <div id="app">
    <Input />
    <List />
  </div>
</template>

<script>
import axios from 'axios';
import Input from './components/Input.vue';
import List from './components/List.vue';
export default {
  name: 'app',
  data () {
    return {
      
    }
  },
  components: {
    Input,
    List
  },
  mounted(){
    axios.get('/getCity').then(res=>{
      console.log('res...', res);
    })
  }
}
</script>

<style lang="scss">

</style>

// 1601N/React/city-tab-react-redux/src/components/app.jsx
import React from 'react';
import Province from './province';
import City from './city';
import '../scss/index.css';
import store from '../store';

export default class App extends React.Component{
    constructor(){
        super();
        // this.state = {
        //     province: [],
        //     city: [],
        //     index: 0
        // }
    }

    componentDidMount(){
        // 获取数据
        fetch('/data/data.json').then(res=>{
            res.json().then(body=>{
                console.log(body);
                store.dispatch({
                    type: 'CHANGE_PROVINCE',
                    text: body
                });

                store.dispatch({
                    type: 'CHANGE_CITY',
                    text: body[0].list
                });
                console.log(store.getState().province.province);
            })
        })
    }

    render(){
        return <div className="index">
            <Province />
            <City data={{name:'刘畅'}}/>
        </div>
    }
}
