// 1601N/React/pre_week3/src/components/Login.jsx
import React from 'react';
import '../scss/login.css';

export default class Chart extends React.Component{
    constructor(){
        super()
        this.state = {
            username: '',
            password: ''
        }
    }

    valueChange(type){
        
    }

    render(){
        return <div className="login">
            <p>登陆页面</p>
            <input type="text" value={this.state.username} placeholder="请输入用户名" 
                onChange={(e)=>{this.valueChange('username', e.target.value)}}/>
            <input type="password" value={this.state.password} placeholder="请输入密码" 
                onChange={(e)=>{this.valueChange('password', e.target.value)}}/>
            <button>登陆</button>
        </div>
    }
}

// 1602E/Project1/cart_vuex/src/components/Login.vue
<template>
    <div>
        <input type="text" placeholder="请输入你的用户名" ref="username">
        <input type="password" placeholder="请输入你的密码" ref="password">
        <button @click="login">登陆</button>
    </div>
</template>

<script>
    export default {
        methods:{
            login(){
                let username = this.$refs.username.value,
                    password = this.$refs.password.value;

                if (!username){
                    alert('请输入用户名');
                    return;
                }
                if (!password){
                    alert('请输入密码');
                    return;
                }

                this.$store.commit('login/doLogin', {
                    username,
                    password
                })
            }
        }
    }
</script>
